version: "3.3"

services:

# NodeJS App's Container
 app:
  image: 192.168.1.19/crudapp:v1
  ports:
    - 8080:4000
  volumes:
    - ./netbanking:/code
  tty: true
  privileged: true
  hostname: node_app

# MongoDB container
 mongodb:
  image: 192.168.1.19/crudmongo:v2
  hostname: mongodb 
  tty: true
  privileged: true

  

   
